name: filebrowser
namespace: operations
deployPhase: services
manifests: true
helmManifests: true
ingress:
  enabled: true
  host: files
  domainType: "internal"
  port: 80
  auth: false
  rateLimit: true
  probe: true
  probePath: /api/health
