controllers:
  main:
    initContainers:
      init-db-dir:
        image:
          repository: busybox
          tag: latest
        command: ["sh", "-c", "mkdir -p /srv/apps/filebrowser && chown 1000:1000 /srv/apps/filebrowser"]
    containers:
      main:
        image:
          repository: filebrowser/filebrowser
          tag: v2.63.0@sha256:1e67e23118d0b14c91e4cffd56dfeb2851fba1673c8379b200a976c52e322446
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
          FB_ROOT: /srv
          FB_DATABASE: /srv/apps/filebrowser/filebrowser.db
          FB_NOAUTH: "true"
        probes:
          liveness:
            enabled: true
            type: HTTP
            port: 80
            path: /health
          readiness:
            enabled: true
            type: HTTP
            port: 80
            path: /health
          startup:
            enabled: true
            type: TCP
            port: 80
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    enabled: false
  apps:
    existingClaim: filebrowser-apps-pvc
    globalMounts:
      - path: /srv/apps
  media:
    enabled: true
    existingClaim: filebrowser-media-pvc
    globalMounts:
      - path: /srv/media
