controllers:
  main:
    containers:
      main:
        image:
          repository: gtstef/filebrowser
          tag: 1.5.4-stable@sha256:a446e25f5d1fe5b961f312659b42eef7df50d854746d2b90fe02bc87d1cb9791
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
          FILEBROWSER_CONFIG: /config/config.yaml
        envFrom:
          - secretRef:
              name: filebrowser-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        probes:
          liveness:
            enabled: true
            type: HTTP
            port: 80
            path: /api/health
          readiness:
            enabled: true
            type: HTTP
            port: 80
            path: /api/health
          startup:
            enabled: true
            type: TCP
            port: 80
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    enabled: false
  fbconfig:
    type: configMap
    name: filebrowser-config
    globalMounts:
      - path: /config
        readOnly: true
  data:
    existingClaim: filebrowser-data-pvc
    globalMounts:
      - path: /home/filebrowser/data
  apps:
    existingClaim: filebrowser-apps-pvc
    globalMounts:
      - path: /srv/apps
  media:
    enabled: true
    existingClaim: filebrowser-media-pvc
    globalMounts:
      - path: /srv/media
