controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/lazylibrarian
          tag: e7c7ce2d-ls262
          digest: sha256:6a7e6c27f39d1284499e88a66b70e5e9b00e8aa02d6a7837dbe4098466b73855
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /
            port: 5299
          readiness:
            enabled: true
            type: HTTP
            path: /
            port: 5299
          startup:
            enabled: true
            type: HTTP
            path: /
            port: 5299

service:
  main:
    controller: main
    ports:
      http:
        port: 5299

persistence:
  config:
    size: 2Gi
  media:
    enabled: true
