apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-enrollment-credentials
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    pilot-password: AgA5HveP8FBBtkkfQ8uMV+7q+4G4RLG22p3yLRbqQwuojP6AyPtmFtxKAKLemgOwovEhXOgy0mNaY0Z3BvwuccNpaVh4M3tAtL+tCrfeisHrvIO9/dab+ULVKyWM9JQTxSSF0+ia2GIeQcWUHx48imGtc7rniMGi0SmFdjMtl1XtownLw5Z7rZ6WA5PcVH3Z0JQlrAY+dMXptyrPdsdwmTUBRUMcm4XA5Kgj8o3f/FQZlNmTnHKRy3G0HeuleGodPnDTBGHxtnshJACe8kLD/gM2+8SHdwQKFbTw0NS9M8kThvMhKYyg9Wi8baZH96aDNzGNB57REfLZjjF+tYbT8Bp02J1mh0i41Ze8LfOekKTcaDYfsL/VQ6Ir5IxGaNPTEUZg/+sAl3bBXdFNjQtdF9YmyBokPGaKXXzbLj3UwWP/Obr9REMkXb7fi6QnXuuO8nYIj9W7tntwMh3tf6uB8jus4ywKqyXeWGmnF9djxjsBgLN/NaJ5x9fpFR1xfQa+hNTmng7J6ncFgKWyHmGUY/FpdcOJzBuhBhLBYYen6fD+XjYukI5mb90l/+n/l1S0tUlT4WzuxDEH6nDDz6hcG0ql7/6oXy8tIlfBJYIrdBMla4RvBVY/4zl3QA0+TH9P6ujwYATVzuy7+l0YjmXQdSp6D5+NXm426NA7BvAic0KzfMXuVCbXlh8EjccBDJKvqqSsLKCYCU5V1fTWpU6ezTfhHt9UrrH1XR0JvmQeXxl9hV1WOaebahCfJRoFT05+6UJTFIvddRa7EauIhwKTudOU
  template:
    metadata:
      name: postgres-enrollment-credentials
      namespace: databases
