name: changedetection
namespace: operations
deployPhase: services
manifests: true
ingress:
  enabled: true
  host: changedetection
  domainType: "internal"
  port: 5000
  auth: true
  rateLimit: false
  probe: true
