name: dispatcharr
namespace: media
deployPhase: services
manifests: true

ingress:
  enabled: true
  host: dispatcharr
  domainType: "internal"
  serviceName: dispatcharr-web
  port: 9191
  auth: false
  rateLimit: false
