controllers:
  main:
    enabled: false
  web:
    containers:
      main:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.27.0@sha256:425129020764037869c7d1a2e74ba57ca640cb5d551ef57d869b745b6ea71c7b
        env:
          TZ: "Asia/Jerusalem"
          DISPATCHARR_ENV: "modular"
          POSTGRES_HOST: "postgres-postgresql.databases.svc.cluster.local"
          POSTGRES_PORT: "5432"
          POSTGRES_DB: "dispatcharr"
          POSTGRES_USER: "dispatch"
          REDIS_HOST: "redis-master.databases.svc.cluster.local"
          REDIS_PORT: "6379"
          REDIS_DB: "4"
        envFrom:
          - secretRef:
              name: dispatcharr-secret
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 9191
          readiness:
            enabled: true
            type: TCP
            port: 9191
          startup:
            enabled: true
            type: TCP
            port: 9191
            spec:
              failureThreshold: 30
              periodSeconds: 5

  celery:
    containers:
      main:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.27.0@sha256:425129020764037869c7d1a2e74ba57ca640cb5d551ef57d869b745b6ea71c7b
        command:
          - /app/docker/entrypoint.celery.sh
        env:
          TZ: "Asia/Jerusalem"
          DISPATCHARR_ENV: "modular"
          DISPATCHARR_WEB_HOST: "dispatcharr"
          DISPATCHARR_PORT: "9191"
          POSTGRES_HOST: "postgres-postgresql.databases.svc.cluster.local"
          POSTGRES_PORT: "5432"
          POSTGRES_DB: "dispatcharr"
          POSTGRES_USER: "dispatch"
          REDIS_HOST: "redis-master.databases.svc.cluster.local"
          REDIS_PORT: "6379"
          REDIS_DB: "4"
        envFrom:
          - secretRef:
              name: dispatcharr-secret
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  web:
    controller: web
    ports:
      http:
        port: 9191

persistence:
  config:
    enabled: false
  data:
    existingClaim: dispatcharr-data
    advancedMounts:
      web:
        main:
          - path: /data
      celery:
        main:
          - path: /data
