name: lidarr
namespace: media
deployPhase: services
commonValuesExtras:
  - templates/media-arr-common.yaml

ingress:
  enabled: true
  host: lidarr
  domainType: "internal"
  port: 8686
  auth: true
  rateLimit: true
