name: qbittorrent
namespace: media
deployPhase: apps

ingress:
  enabled: true
  host: qbittorrent
  domainType: "internal"
  port: 8080
  serviceName: qbittorrent-main
  auth: true
  rateLimit: true
