# CSI prerequisite, owned by the foundation sealed-secrets Application.
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-api-trust
  namespace: csi-proxmox
data:
  proxmox.pem: |
    -----BEGIN CERTIFICATE-----
    MIIE9jCCAt6gAwIBAgIBATANBgkqhkiG9w0BAQsFADB2MSQwIgYDVQQDDBtQcm94
    bW94IFZpcnR1YWwgRW52aXJvbm1lbnQxLTArBgNVBAsMJDBhOGQ2ZDE2LTk3ZTgt
    NGI5OS1iNTJlLTJlZDNmYjBhYzA1NTEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFu
    YWdlciBDQTAeFw0yNTA2MTQwMDU2MzZaFw0yNzA2MTQwMDU2MzZaMFkxGTAXBgNV
    BAsTEFBWRSBDbHVzdGVyIE5vZGUxJDAiBgNVBAoTG1Byb3htb3ggVmlydHVhbCBF
    bnZpcm9ubWVudDEWMBQGA1UEAxMNcHZlLmhvbWUuYXJwYTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAK33sGvZC9Hfuh9H94JPavhFKzX1mB+xs13PfnPl
    6/228ouzqls74n+vPAd/kr15NuqJv9MHRsyRlG//HZw3Y6uqMAvGQ3HitukEOJgb
    9r1xzEGItJKL79WTJYPspXwd5ED3IRboSTUjBfYmHW5/OgpjcUecEqANbuidzwTL
    KU1WQT62nUTUhErwFvCpjWgzNv34+uYzK+8tRcalCrnWIqCodvazK5C8nXiWiKhQ
    k8oSMqn/dWPKij1u53V05l0cSucESi9G79KCzrIwZ7t3W2+bPr3eiX2Iz4HmHu4H
    6DYnodACD2FU8hYrDG/wt70DyQBv6Bun8dlS3dqhxNhgFAUCAwEAAaOBqzCBqDAJ
    BgNVHRMEAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMEYGA1UdEQQ/MD2HBH8AAAGH
    EAAAAAAAAAAAAAAAAAAAAAGCCWxvY2FsaG9zdIcECgkJFIIDcHZlgg1wdmUuaG9t
    ZS5hcnBhMB0GA1UdDgQWBBRaitAJeada8fXtkAkLiszcqeB6nDAfBgNVHSMEGDAW
    gBR8iYZlt1fYqUeDnYhJzoRN0LcRRjANBgkqhkiG9w0BAQsFAAOCAgEAt2+8Z3jo
    KcBeAtAfKwegwm08Oe4SwMEf54c16OCBOneiaaLApOqWBN7Q+r/5qnrwUW5qhR5j
    Sy3bf1WNVtUFx3nbMZ7Up9a34RhuHxNC99tnzSINcMMER36zTgMa74brd5DcVFPS
    G7n4SNaQ7uxfEiMALiJ4ZPIQmdzuTBK8i0LFLQKSCkZ84YkDsqgb2Nq+F0PTFvIJ
    wt8RfDy9uC4viJBdZc67Ac53Seodydod6i4suGMadU0cA/vtjVWufB9pa+gQnzJp
    BYJ1yBdz8iK67XIN79UCGu6cS9/hRL0XXiM1dDXsKUOAl58Q8I5cWeQOLExmlkHD
    oZ0fSWN4EIMYUciv919Y2zwWUGxuamePktFtEeSDrvoXV8J8KkrS11gkiVYAFb35
    a2jZaBuqix028DkLw5ZavTQl2x4zU85A8P/OoCxXfyMMZ0IFeC1SqoCRuSV4zVXM
    O8p7B1JTw24EXJWNRGIxhH0K1+P47fQKVmEgpNyAfbbCQ2xpmrZDcxnCOkm7uM50
    YudhDEh7Pn45EARDhxUzh8AiV8Ds2uemf4ijZxr2MZ7oqrU12c+lKw2MFee4eJqa
    akYXMzvtEFLkhivA+psdUE65A6682nGWIdCIDDvfSXWRfJFNHaadX+holMdzBteB
    52CD0+4TUb+xoINUM0f8pNf+wrueRPtU8Wo=
    -----END CERTIFICATE-----
