controllers:
  main:
    serviceAccount:
      name: homepage
    containers:
      main:
        env:
          HOMEPAGE_ALLOWED_HOSTS: "starktastic.net"
        envFrom:
          - secretRef:
              name: homepage-secrets
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthcheck
                port: 3000
                httpHeaders:
                  - name: Host
                    value: starktastic.net
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthcheck
                port: 3000
                httpHeaders:
                  - name: Host
                    value: starktastic.net
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/healthcheck
                port: 3000
                httpHeaders:
                  - name: Host
                    value: starktastic.net
              failureThreshold: 30
              periodSeconds: 5

persistence:
  homepage-admin-config:
    enabled: false
  homepage-admin-background:
    enabled: false
  homepage-config:
    enabled: true
    type: configMap
    name: homepage-config
    globalMounts:
      - path: /app/config/settings.yaml
        subPath: settings.yaml
        readOnly: true
      - path: /app/config/services.yaml
        subPath: services.yaml
        readOnly: true
      - path: /app/config/bookmarks.yaml
        subPath: bookmarks.yaml
        readOnly: true
      - path: /app/config/widgets.yaml
        subPath: widgets.yaml
        readOnly: true
      - path: /app/config/kubernetes.yaml
        subPath: kubernetes.yaml
        readOnly: true
      - path: /app/config/custom.css
        subPath: custom.css
        readOnly: true
      - path: /app/config/custom.js
        subPath: custom.js
        readOnly: true
      - path: /app/config/docker.yaml
        subPath: docker.yaml
        readOnly: true
  homepage-background:
    enabled: false
