apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    name: authentik
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-backup
  labels:
    name: cert-backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
---
apiVersion: v1
kind: Namespace
metadata:
  name: operations
  labels:
    name: operations
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    name: traefik-system
