name: radarr
namespace: media
deployPhase: services
commonValuesExtras:
  - templates/media-arr-common.yaml

ingress:
  enabled: true
  host: radarr
  domainType: "internal"
  port: 7878
  auth: true
  rateLimit: true
