controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 6.2.1@sha256:7b45af3b660f5ff5f7d6d625bfa99960cb9265e902f1bef136486f6d2be73ee9
        probes:
          liveness:
            port: 7878
          readiness:
            port: 7878
          startup:
            port: 7878
service:
  main:
    ports:
      http:
        port: 7878
