controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 6.0.4
          digest: sha256:a360633a3682d41e96f71a07ff36ecbdf2394a9628465b84b0a8437087715b41
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

persistence:
  media:
    enabled: true
