controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/radarr
          tag: 6.1.1@sha256:659e5f20500948b1491f31dd85c6f99a43508ce3e46595793e1e15aa955bf6d7
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 7878

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

persistence:
  media:
    enabled: true
