---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-secret
  namespace: media
spec:
  encryptedData:
    BAZARR_APIKEY: AgBYjA286ORxJOMMNEjapUlWL8gH8Tla5szdEoFEmnF5HIO2RVsEXW5hHKxEsz+k1N0jiHYrX/sTaXJJ+vqnVdqlg76OBBzqPN7G8mDZIXnqBa6tSw/6cvrJkQoCA99IGukNxng2BTzxWooyorVQ8JjIL2QTaAVIPWJRhAaNf+j8cAhjg2wqmviFJL4kFrYjcM8RcgCFUFmgwlJWbt78fQfEC5Ck/lQcxle9lRcDJBXchJtGn8a7Zu5Xlltjk12945yG/76/3Pk71xHKiuK+qGSayjanr/sbGADo8NFlyaSdNCZ9knbrJ5jMJseJXHtEbZdFeVJ+0jTaBCi9tU7fGtRnsvsuHOWEdr0c5SwhnsOqamcwfX4SpOREp8e2Qgv028lf7JFk1LLtuAXNKJr8NKd0cXO4dGo/dV1KdzpfD10N5eTvsDje/TGhnRz/UkXVZuuFyZ+P/b3JD28KYs+nmoZLR7tmzopgAZG25HG4mP876S9xnQ3CnZ3939KC/J1WzUBVmZtBGVM8z1KYat+n5BcFydhoCFLxLStOWFgQlrpZvCEEEqs/fLm1dzyHyMgSIRi6gUDVCDWowmZsQ3PVZQlhAnEYt+JXUNJWBFFbV4rwvMKuagJpwXDd/Plj9x9nWgID0I9E8JrqGiiIu4zR/1BzHJUoUCoGF0Vgpi87dDtKOWxUQ+09nnA+80X7gAkWH1u6eIHNlFtSZ0JkMOVAU+GJw12jb1KpXIVBFTFeYGLp1g==
    JELLYFIN_API_KEY: AgACr66isynF4+qOLhWnsuUQppMSrJmbhxbkro7Q5RfbndTb3XecykZU+cFbxvdCT0YvTAg41sE0uFgsINSw1vuHTpoMjGuqQwMAgxecSFkkqffBN1UyDxtcjCle0wtvi5PbNMLGF/okenM6uhAvly6MHIwvRkiwYe4dOJhzUT/yk9Nf7AiMTpjCllvCCPnbYlcgZFwyFRfwXyrjtfOiznPFxldrLVw4JRV/AWDxzzanyTy5w4Uyw+g3PcgwuTb1rfbAXySz/nAZmRhBnImVap7csWq2EPfsbYq0yuh+MkuIkCQ7kNuua0MaCzne4nJzh8rA2XmIaMyEyq77JuyZutMOzTqBKdg8Nh7SSQRMxgTaIDYpn5XInmeWVCk/kUX+9M6Ag64Cr6tVakS6NmR7tuqiZQpFHCtoVv1om5PDk8uGxb0xbYmXJvvLiBfxUHv9VAO4V4wGOeWYZg6nthzovluSPh/7lXB+k81vgVcezqCpTfZueiaGqiUQAvqpaBeT2b3+aU/BWQsTV4yKROOmMfW6XoMZ+OscKhYcrp72RlfMIOsvOhq7JvT9DknV/qFX9mG8w5aeSAnloWKVAlai2n6KjMa8bT0BFrrKu1+06Tmja7YIk/owYMZM5p8dRT3eNAsuVvQNbhtlv+mjlYjInIG02p8rM+gCCVpFtURCzusk0Y4giDl4XGW55sKy/1H3Fi0VXipQUvd5peOv/GyZnGU23Npt2b9RZqzCDBi5cM3rEQ==
  template:
    metadata:
      name: bazarr-secret
      namespace: media
