name: vaultwarden
namespace: operations
deployPhase: services
manifests: true
ingress:
  enabled: true
  host: vaultwarden
  domainType: "internal"
  port: 8080
  auth: false
  rateLimit: true
  probe: true
