nfs:
  server: 10.9.8.30 # source: globals.yaml → global.network.nfs.server
  path: /mnt/apps/pv
storageClass:
  name: nfs-pv # source: globals.yaml → global.storageClass
  defaultClass: true
  reclaimPolicy: Retain
  archiveOnDelete: false
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  mountOptions:
    - nfsvers=4.1
    - noatime
    - hard
    - rsize=1048576
    - wsize=1048576
