controllers:
  main:
    containers:
      main:
        image:
          repository: sdblepas/cineplete
          tag: v4.5.2@sha256:4bf150c7e1f3b3056ff6cc36b6b6b2945b8878119515123bf60b429ce91e3a05
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8787
          readiness:
            enabled: true
            type: TCP
            port: 8787
          startup:
            enabled: true
            type: TCP
            port: 8787
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8787

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-pv"
    size: 1Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /data
