controllers:
  main:
    containers:
      main:
        image:
          repository: sdblepas/cineplete
          tag: v4.6.3@sha256:f12e32b01df2d6727948e8429ad357d54e8fc1489f375372357ab254cc0ef78a
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8787
          readiness:
            enabled: true
            type: TCP
            port: 8787
          startup:
            enabled: true
            type: TCP
            port: 8787
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8787

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-pv"
    size: 1Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /data
