controllers:
  main:
    containers:
      main:
        image:
          repository: sdblepas/cineplete
          tag: v4.5.1@sha256:8e61d95978b8b0512c3964efe824bc9f79f01127b8888e09c56fe9c652e7fd3e
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8787
          readiness:
            enabled: true
            type: TCP
            port: 8787
          startup:
            enabled: true
            type: TCP
            port: 8787
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8787

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: "nfs-pv"
    size: 1Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /data
