apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-automation
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: iscsi-pv
  resources:
    requests:
      storage: 5Gi
