controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/calibrain/shelfmark
          tag: v1.2.2@sha256:ef74ed98291a46ed7c6b04f2762acfd47da36a232b4dcdb6591dd3c5661ca38d
        env:
          FLASK_PORT: "8084"
          INGEST_DIR: "/books"
          HIDE_LOCAL_AUTH: "true"
          OIDC_AUTO_REDIRECT: "true"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084
          readiness:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084
          startup:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084

service:
  main:
    controller: main
    ports:
      http:
        port: 8084

persistence:
  ingest:
    existingClaim: cwa-book-ingest
    globalMounts:
      - path: /books
  media:
    enabled: true
