controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/calibrain/shelfmark
          tag: v1.3.15@sha256:dae6e16fc40f42b2558d9f47d05e4ba7a7d268d23365a7c3eba266055249a124
        env:
          FLASK_PORT: "8084"
          INGEST_DIR: "/books"
          HIDE_LOCAL_AUTH: "true"
          DISABLE_LOCAL_AUTH: "true"
          OIDC_AUTO_REDIRECT: "true"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084
          readiness:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084
          startup:
            enabled: true
            type: HTTP
            path: /api/health
            port: 8084

service:
  main:
    controller: main
    ports:
      http:
        port: 8084

persistence:
  ingest:
    existingClaim: cwa-book-ingest
    globalMounts:
      - path: /books
  media:
    enabled: true
