name: home-assistant
namespace: home-automation
deployPhase: services

ingress:
  enabled: true
  host: ha
  serviceName: home-assistant-main
  domainType: "internal"
  port: 8123
  auth: false
  rateLimit: false
