controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2026.4.2@sha256:4c940155cfd5b0187a6faee2db5d52b98bb573edc1aeee95d0818bb17b6534d7
        env:
          PUID: null
          PGID: null
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8123
          readiness:
            enabled: true
            type: TCP
            port: 8123
          startup:
            enabled: true
            type: TCP
            port: 8123
            spec:
              initialDelaySeconds: 10
              failureThreshold: 60
              periodSeconds: 10

defaultPodOptions:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  securityContext:
    fsGroup: 0

service:
  main:
    controller: main
    ports:
      http:
        port: 8123
  lan:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: "{{ .Values.global.network.loadBalancers.homeAssistant }}"
    ports:
      http:
        port: 8123
      mdns:
        port: 5353
        protocol: UDP

persistence:
  config:
    enabled: false
  home-assistant-config:
    existingClaim: home-assistant-config
    globalMounts:
      - path: /config
  media:
    enabled: false
