---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: operations
spec:
  encryptedData:
    SEARXNG_SECRET: AgAV9BTy32XYXRr2L/lz+zxudYiqGNCIlb3biw5xUnZHbp9gl5HsGx02mH9qyZ10HJu/Rycq1qyY6TrUGDs5DL9wLrccUsraE1RZPI/MvV2NqSh+eCWkBH5gON69PfNcL2DH2pGZyCzsYswjoK1r0PQWfr3U8lLWyShVOwPa+R4H+Ak02NOZkp9a0wdU8ZZ43qNESI8wjAcsD1R4vf5fIQZS4oKQjEf/02BOEWLjUlke3GZ/UkanCl6NRQ7RlN5ZUORPPT3BnnpcERTvyfzAqYANhkgN7nqFMt1Mcujbb3xHM5B+n2DTzFuwimlJckp8SOvA40A+TwMBsp4gE75TLenT3sjsAgltQFKIbX+kxM1G1jxxE5FaQfaGcWeukwSq/oASKD6nvdSYEzcQ/uGS6zcfYEKRHZZ+IKJi40kIfYbiaetnm8scElRvIZ87KA0oaH0TjgSBhRzrgDqNy5dVq6+Rtc4yM6Mdm/h9YJP0exvIhqHBIrmWPMR8rQRXcFIsyHGjk1EkPYBZCeu9SBTW+6l51np3fOrhvCg+MztCdzR7QyNXcuV1i5xFp9YVlOZAbwuFVj/2dQeQcJz0Pb06fWuI5Mgbpa4VB9IyOpV/SRPlJtmZFKxAUYVMvfwvHXv+qD+dIUGxNbbmbdQ+dzS9VbnMzsGqeyeDnh4/G7EvxfeUoRQnfXYbGuoYDQiC0lPUZKDB5brA3dnvkNdxFS//JPAED+bL+Yiac2fyuRW0TWOfwMt1BKywpFoSVyJC5lx8AWiuduBoTyQEfe2y0GueaArA
  template:
    metadata:
      name: searxng-secret
      namespace: operations
