apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
  namespace: databases
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pg-backup
              image: postgres:18-alpine
              command: ["/bin/sh", "/scripts/backup.sh"]
              env:
                - name: PGHOST
                  value: postgres-postgresql.databases.svc.cluster.local
                - name: PGPORT
                  value: "5432"
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-admin-secret
                      key: postgres-password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
                - name: script
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: pg-backup
            - name: script
              configMap:
                name: pg-backup-script
                defaultMode: 0755
