apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 1Gi
