apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-enrollment-pilot-secret
  namespace: operations
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAh2Hl8uGGBmTARDuyqgcH9EJhwE7ByhWEf7+hdmGkzR4Ms6wtbnDK/JyKh5Qu/5OBPvi3ZyVUSQrKm/bCI8URQRVW91wJ6+EDSTrRumaFQWaaH/FwKGURktH05+t2+zXHX5E3EXw8/HDTDB8PxK18VzMjsZP9GlqtANR5XW1Kd8DedfCzbpvdGqViCuWTU9dRzy10v3sfUDXE2QtxA4yWKpHt/HuIUj2vdpt40K76eVw7n0MZZg1PskPImJu88Xm+pOB6w0AhlMsvfikQ3Oz5BiFZ4kLQlPEDGhEjJUoVILaqOYP9rM1QMVoI/iHsSm43/p3qqSfFi+1x7ZivafbIdETCOCB6ha6caHFwCwHDuZE/cwBwOO4nTE9O3qrRIomYNyJKckmlvAGUw3MN36DswdLdkFZTQ4utQSJT90fVlJHpJkDvCZkXtec0dbx1/MBLFJOBPwOk8VRcBxnRRIWwkREsefcikLyyDw80EukYxpfs6qDMFmtD1wnKBcnUP+LfZQYqDfulwmPYRRZdy3EmKQfQr1YvXpJQ54JGe5Wrj/UfV/yz620mpy05URe4n4berS5FyRB6qrAs2Ir6j/maz1bYch26+uxeB1OscGJEBBksMxrZRc5eJCeP6cYoHXBtFWcwmiquUwRESzI6La3KP9+0XqQSSwe3PMTLQznt0mKCg3v/eJJ4ZlAVdQxIdS1Qka0QC3AZxA2Gzu6GaqjOr4GVFQ2TWAs23Ts/eqXluiyvdz5sion6RCwbZUqLz9I1bLqpwwpiWiwL9NHnmM9gC
  template:
    metadata:
      name: postgres-enrollment-pilot-secret
      namespace: operations
