apiVersion: v1
kind: Service
metadata:
  name: kube-vip-svc-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-svc
    app.kubernetes.io/component: metrics
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kube-vip-svc
  ports:
    - name: metrics
      protocol: TCP
      port: 2113
      targetPort: 2113
