apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-vip-cp
  namespace: kube-system
  labels:
    app: kube-vip-cp
    app.kubernetes.io/component: metrics
spec:
  jobLabel: kube-vip-cp
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-vip-cp
      app.kubernetes.io/component: metrics
