apiVersion: v1
kind: Service
metadata:
  name: kube-vip-cp-metrics
  namespace: kube-system
  labels:
    app: kube-vip-cp
    app.kubernetes.io/component: metrics
spec:
  clusterIP: None
  selector:
    app: kube-vip-cp
  ports:
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
