controllers:
  main:
    containers:
      main:
        image:
          repository: mpepping/cyberchef
          tag: latest@sha256:c839936366478bb8615ac34c0919326b1d0079a3021eb7cd0db48aacf877235d
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8000
          readiness:
            enabled: true
            type: TCP
            port: 8000
          startup:
            enabled: true
            type: TCP
            port: 8000
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: false
  media:
    enabled: false
