controllers:
  main:
    containers:
      main:
        image:
          repository: mpepping/cyberchef
          tag: latest@sha256:455c28870913cacedd3b98dde636a74f6e2392ddfae2e09331a95bc5c7a9e2d7
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8000
          readiness:
            enabled: true
            type: TCP
            port: 8000
          startup:
            enabled: true
            type: TCP
            port: 8000
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: false
  media:
    enabled: false
