controllers:
  main:
    containers:
      main:
        image:
          repository: mpepping/cyberchef
          tag: latest@sha256:75c310366caa5ec0691c6300c396905ee656945a3810b46a02e546942c6d7d1a
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8000
          readiness:
            enabled: true
            type: TCP
            port: 8000
          startup:
            enabled: true
            type: TCP
            port: 8000
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: false
  media:
    enabled: false
