name: paperless-ngx
namespace: operations
deployPhase: services
manifests: true
ingress:
  enabled: true
  host: paperless
  domainType: "internal"
  port: 8000
  auth: false
  rateLimit: true
  probe: true
