name: prometheus-blackbox-exporter
namespace: monitoring
deployPhase: services
manifests: true
chart:
  repo: https://prometheus-community.github.io/helm-charts
  name: prometheus-blackbox-exporter
  version: 11.13.0
