controllers:
  main:
    containers:
      main:
        image:
          repository: listmonk/listmonk
          tag: v6.0.0@sha256:d9c37805fdc486e5ca28d995c71757b60cac978e063d91849e49e7163ef3e6f0
        command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
        envFrom:
          - secretRef:
              name: listmonk-secret
        probes:
          liveness:
            enabled: true
            type: HTTP
            port: 9000
            path: /health
          readiness:
            enabled: true
            type: HTTP
            port: 9000
            path: /health
          startup:
            enabled: true
            type: TCP
            port: 9000
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 9000

persistence:
  uploads:
    existingClaim: listmonk-uploads
    globalMounts:
      - path: /listmonk/uploads
