---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: media
spec:
  encryptedData:
    DB_PASSWORD: AgC0fjS5iDD+CbrT3tg2llKRN0t4Gi6YnI6Lcno2fCQ2buqFi/Vn8SnBQAIWAKIPhZJjNikZDckk/PVeFqiLd/Sqjtk9LTrot3wLe60NzOgDiUY1ZPEj5WFQYi7YiXJA8F6a1LFZD9haz+DENEYLs8Ew9rSrpEHukmUl/69eUFSCrttgTc82bT3IasS4gKWQsSggviMNg96AklkQrs/7aSHT+HYofFyT6NHaJoj7dVSTgz6FeOkYlNFXRvaPOrHTCr5Zq+4Ycl4dbSohPs2r5j7MOKvBtYLi4RE2YKX3mS03S70eki2s9M4sgMwFtSEK4OuNUrVj4mtFrhZSbCpwb/JGWHmqsKBF1EqiBm5Qo+w8wkNrIMm3OpRUahiwO1QRM2X7Yu9DeTVZfPLd3Vs/WhGiyPAbUz3aBh6Kgvm9iTTYElaLUbTqwKFskbKhS/HQ2I5aehpqsnWXi6bSzSTX6VhkLNGq/Wuh60nKEEmrkulFaauKPErGsCdha9qY5jy+H5DH4Hh2r/uV/KQwQURb5zccg3hRFmuiLERV8sRYD0733Znt/TU97lgfZIDNLY0fBFffFL9D4ekjvX9ovMCxrQnvkAvPDH1JqFEBmmCGEHon/K71ZvAjw8fEeVTIWaU+P8+ek6gs1j2uhyPP6w7HdNBueZs9B0YtnyTz3DdigANrdL1AghyH6AwEez+INpru37TAe1KEzUB77JwoojRk7YhsMi9vI8EiOKDdfbA0zQ886g==
    REDIS_PASSWORD: AgBAVCaj5Z8IsdMKa0JpUvGC7a1q+TlMVUR+eg7MVja1c84Aq6HZaV9PNFjcXtZb10cdnNDcYmeDVE4TZwwySAkfjnO60XiJEd5KLJWlSu2Ef70WQS0snX+1WewTp99Qls3AMfqmnV3PGS0147SoFTr51PeSm8SvLEiZgLkK4lpQKxr42YDis23qiUPGWjQid4xBeuFZHsNVTkBLm4ERpnCfSRxBxklOEezL75IHOzIV37e8C/iaSiSPHVlle8HmkGPCjWCCsNDGmPvKHomCTAZDWt2hDUnZnQh4xYXfWEDSQVLWfqqMqWSFahI54xXw6/i3GYQb4O5z5OhkhJmbtl+y9w17DS7YxmA7nblQMiUkLg+9pSI9Rx+xj9hxX5DWqDJ2ibEPxQYLm4nEQhmLW1qsWLwjC1sclKPQhp6L9uUnqtgV3Pq6B7gffJget0YBQNciTYpeI6s+C91eXJUoPMN8pS4DduCxRfybMlg9CJeMzFbhof0MlGW57vuYunJcyN+d/s4sSJQvp9hBbj1Qop1llNkwk9ws3rtz10aCQzDqK0HSdlHVZbOZXUie76xg9fC4hV/y/2SepOVX3fMu1aULU/r4N+dOaU6QWMHSUWYlpj1nEcVez10QuYmJeQurZfKTyKo9PIna0a2EHstTz/AJwz3WrwbvzWjpPRJxIeaGSJXYjG/Kx3oFteeS4W8KfVxbrsRo65c7LtyIcEDTrOecI/e8nA==
  template:
    metadata:
      name: immich-secret
      namespace: media
