controllers:
  main:
    pod:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    containers:
      main:
        image:
          repository: mccloud/subgen
          tag: 2026.04.1-cpu@sha256:82bb39371acc8e5befe51901278260863b5174fc223c502e2a5ace769eebcb06
        env:
          WHISPER_MODEL: "small"
          TRANSCRIBE_DEVICE: "cpu"
          TRANSCRIBE_OR_TRANSLATE: "translate"
          WHISPER_THREADS: "6"
          CONCURRENT_TRANSCRIPTIONS: "1"
          CLEAR_VRAM_ON_COMPLETE: "True"
          MODEL_CLEANUP_DELAY: "30"
          UPDATE: "False"
          DEBUG: "False"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /status
            port: 9000
          readiness:
            enabled: true
            type: HTTP
            path: /status
            port: 9000
          startup:
            enabled: true
            type: HTTP
            path: /status
            port: 9000
            spec:
              initialDelaySeconds: 10
              failureThreshold: 60
              periodSeconds: 10

service:
  main:
    controller: main
    ports:
      http:
        port: 9000

persistence:
  config:
    enabled: false
  media:
    enabled: true
  models:
    type: emptyDir
    globalMounts:
      - path: /subgen/models
