driver:
  config:
    driver: node-manual
    node:
      format:
        ext4:
          customOptions:
            - -n
      mount:
        checkFilesystem:
          ext4:
            enabled: false
csiDriver:
  name: org.democratic-csi.retained
  attachRequired: false
controller:
  enabled: false
node:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"
    storage.starktastic.net/iscsi-ready: "true"
  cleanup:
    image:
      registry: docker.io/library/busybox
      tag: 1.37.0@sha256:7a3ebe5bfd1a4a19797d20b0c0bb39d44393e9a03fd852c0865b0f540d868df0
      pullPolicy: IfNotPresent
  driver:
    image:
      registry: ghcr.io/democratic-csi/democratic-csi
      tag: v1.9.5@sha256:746bf6b373ae75f5da8b1e412d13c3e8d0e2e1494654268b9dd6fe1f1e55aade
      pullPolicy: IfNotPresent
  driverRegistrar:
    image:
      registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.9.0@sha256:4da2674bae016b1011c2042cb719cffd9a80d34f3cf933c705b425054f86cea9
      pullPolicy: IfNotPresent
storageClasses: []
csiProxy:
  image:
    registry: ghcr.io/democratic-csi/csi-grpc-proxy
    tag: v0.5.7@sha256:78e86badadfe67a9afdbe2c9a3afc02bc50aa43b86203c9ca6fc046ab3519e3f
    pullPolicy: IfNotPresent
