controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8191
          readiness:
            enabled: true
            type: TCP
            port: 8191
          startup:
            enabled: true
            type: TCP
            port: 8191
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8191

persistence:
  config:
    enabled: false
