controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/flaresolverr/flaresolverr
          tag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8191
          readiness:
            enabled: true
            type: TCP
            port: 8191
          startup:
            enabled: true
            type: TCP
            port: 8191
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8191

persistence:
  config:
    enabled: false
