apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-backup
  namespace: cert-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: 1Mi
