apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.50.0
    helm:
      values: |
        env:
          email: "benfaingold@gmail.com"
        existingSecret: "pgadmin-secret"
        secretKeys:
          pgadminPasswordKey: "password"
        envVarsExtra:
          - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
            value: "['webserver', 'internal']"
          
          - name: PGADMIN_CONFIG_WEBSERVER_REMOTE_USER
            value: "X-authentik-email"
          
          - name: PGADMIN_CONFIG_WEBSERVER_AUTO_CREATE_USER
            value: "False"
          
          - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
            value: "False"
        persistentVolume:
          enabled: true
          storageClass: "nfs-pv"
          size: 1Gi
        serverDefinitions:
          enabled: true
          resourceType: ConfigMap
          servers:
            primaryDB:
              Name: "Starktastic Postgres"
              Group: "Servers"
              Username: "postgres"
              Host: "postgres-postgresql"
              Port: 5432
              SSLMode: "prefer"
              MaintenanceDB: "postgres"
        securityContext:
          fsGroup: 5050
          runAsUser: 5050
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
