controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.4.0
          digest: sha256:cf1afc960655fb7a4b2b84eba851df95407e57efb71eed8d0a173254b48d8335
        env:
          CRON_SCHEDULE: "@daily"
          RECYCLARR_CREATE_CONFIG: "false"
        envFrom:
          - secretRef:
              name: recyclarr-secret
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    enabled: false

persistence:
  config:
    enabled: false
  config-dir:
    type: emptyDir
    globalMounts:
      - path: /config
  recyclarr-config:
    type: configMap
    name: recyclarr-config
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
