controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.6.0@sha256:3c38ceeb54438dd8327e4e65c9b48ba601a6d20fff833342d93c9b0bc4b1930b
        env:
          CRON_SCHEDULE: "@daily"
          RECYCLARR_CREATE_CONFIG: "false"
        envFrom:
          - secretRef:
              name: recyclarr-secret
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    enabled: false

persistence:
  config:
    enabled: false
  config-dir:
    type: emptyDir
    globalMounts:
      - path: /config
  recyclarr-config:
    type: configMap
    name: recyclarr-config
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
