controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 5.1.4@sha256:a89108b1bf43de072a35a59a3ee41b97b564538faae5cbb3f6c803aa7f5fd9f7
        env:
          WEBUI_PORT: "8080"
          DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8080
          readiness:
            enabled: true
            type: TCP
            port: 8080
          startup:
            enabled: true
            type: TCP
            port: 8080
            spec:
              failureThreshold: 30
              periodSeconds: 5
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
  bittorrent:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: "{{ .Values.global.network.loadBalancers.qbittorrent }}"
    ports:
      bittorrent-tcp:
        enabled: true
        port: 56881
        protocol: TCP
      bittorrent-udp:
        enabled: true
        port: 56881
        protocol: UDP
persistence:
  media:
    enabled: true
