controllers:
  main:
    pod:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    initContainers:
      clean-stale-locks:
        image:
          repository: busybox
          tag: stable
        command:
          - sh
          - -c
          - |
            rm -fv /config/qBittorrent/lockfile /config/qBittorrent/ipc-socket
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/qbittorrent
          tag: 5.2.1@sha256:715d2bfbcf1cd3d734cbbd4fbd599eb7ea0642eaa079a372dd0d343f59516700
        env:
          WEBUI_PORT: "8080"
          DOCKER_MODS: "ghcr.io/gabe565/linuxserver-mod-vuetorrent"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8080
          readiness:
            enabled: true
            type: TCP
            port: 8080
          startup:
            enabled: true
            type: TCP
            port: 8080
            spec:
              failureThreshold: 30
              periodSeconds: 5
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
  bittorrent:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/loadBalancerIPs: "{{ .Values.global.network.loadBalancers.qbittorrent }}"
    ports:
      bittorrent-tcp:
        enabled: true
        port: 56881
        protocol: TCP
      bittorrent-udp:
        enabled: true
        port: 56881
        protocol: UDP
persistence:
  media:
    enabled: true
  incomplete:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: qbittorrent-incomplete-pvc
    advancedMounts:
      main:
        main:
          - path: /downloads/incomplete
            subPath: qbittorrent
