name: qbittorrent-ru
namespace: media
deployPhase: services
baseApp: services/media/qbittorrent
valuesOverride: true

ingress:
  enabled: true
  host: qbittorrent-ru
  domainType: "internal"
  port: 8080
  serviceName: qbittorrent-ru-main
  auth: true
  rateLimit: true
