# Override values for qbittorrent-ru (base: services/media/qbittorrent)
# Only the delta from the base service's values.yaml
service:
  bittorrent:
    annotations:
      metallb.universe.tf/loadBalancerIPs: "{{ .Values.global.network.loadBalancers.qbittorrentRu }}"
    ports:
      bittorrent-tcp:
        port: 56882
      bittorrent-udp:
        port: 56882
