controllers:
  main:
    initContainers:
      copy-config:
        image:
          repository: busybox
          tag: stable
        command:
          - sh
          - -c
          - cp /config-source/config.yml /config/config.yml
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
    containers:
      main:
        image:
          repository: ghcr.io/stuffanthings/qbit_manage
          tag: v4.7.0@sha256:8786f2efc6fb8e26281f09bf6c5d0004e2d2420fd4781af0aed123ae01558e21
        env:
          QBT_SCHEDULE: "30"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    enabled: false

persistence:
  config:
    enabled: false
  config-dir:
    type: emptyDir
    globalMounts:
      - path: /config
  qbit-config:
    type: configMap
    name: qbit-manage-config
    advancedMounts:
      main:
        copy-config:
          - path: /config-source/config.yml
            subPath: config.yml
            readOnly: true
  media:
    enabled: true
