apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-block
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: proxmox-retained
  claimRef:
    name: jellyfin-config-block
    namespace: media
  csi:
    driver: csi.proxmox.sinextra.dev
    fsType: ext4
    volumeHandle: homelab//k3s-block/9999/vm-9999-jellyfin.raw
    volumeAttributes:
      storage: k3s-block
      cache: none
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values: [homelab]
            - key: topology.kubernetes.io/zone
              operator: In
              values: [pve]
