apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-block
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  storageClassName: proxmox-retained
  volumeName: jellyfin-config-block
  resources:
    requests:
      storage: 64Gi
