controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/alexta69/metube
          tag: "2026.03.03"
          digest: sha256:079c0100fec65a972dd7bf8fed9474a2e947c6badb875465878a389bb3a0c163
        env:
          DOWNLOAD_DIR: "/data/downloads/metube"
          STATE_DIR: "/data/downloads/metube/.metube"
          DELETE_FILE_ON_TRASHCAN: "true"
          DEFAULT_THEME: "auto"
          CHOWN_DIRS: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8081
          readiness:
            enabled: true
            type: TCP
            port: 8081
          startup:
            enabled: true
            type: TCP
            port: 8081
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8081

persistence:
  config:
    enabled: false
  media:
    enabled: true
