controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/alexta69/metube
          tag: 2026.03.06
          digest: sha256:cf1a23ab3bdd98871dde90291e15ad4b9638ac47b4edd9a0139accd462ea3ed5
        env:
          DOWNLOAD_DIR: "/data/downloads/metube"
          TEMP_DIR: "/data/downloads/metube/.tmp"
          STATE_DIR: "/data/downloads/metube/.metube"
          DELETE_FILE_ON_TRASHCAN: "true"
          DEFAULT_THEME: "auto"
          CHOWN_DIRS: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8081
          readiness:
            enabled: true
            type: TCP
            port: 8081
          startup:
            enabled: true
            type: TCP
            port: 8081
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8081

persistence:
  config:
    enabled: false
  media:
    enabled: true
