controllers:
  main:
    containers:
      main:
        image:
          repository: libretranslate/libretranslate
          tag: v1.9.6@sha256:1de2d7056bb8ad607a412f4563d9abe324ff632b43b5be9428bcc8e213aebb32
        env:
          LT_LOAD_ONLY: "en,he,ru"
          LT_DISABLE_WEB_UI: "true"
          LT_THREADS: "4"
          LT_UPDATE_MODELS: "true"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /languages
            port: 5000
          readiness:
            enabled: true
            type: HTTP
            path: /languages
            port: 5000
          startup:
            enabled: true
            type: HTTP
            path: /languages
            port: 5000
            spec:
              initialDelaySeconds: 30
              failureThreshold: 120
              periodSeconds: 10

service:
  main:
    controller: main
    ports:
      http:
        port: 5000

persistence:
  config:
    enabled: false
  libretranslate-models:
    type: persistentVolumeClaim
    size: 2Gi
    accessMode: ReadWriteMany
    globalMounts:
      - path: /home/libretranslate/.local
