controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 2.3.0
          digest: sha256:a8fe7b9c502f979146b6d0f22438b825c38e068241bb8a708c473062dffdbb03
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696

service:
  main:
    controller: main
    ports:
      http:
        port: 9696
