controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 2.3.5@sha256:35f48abb3e976fcf077fae756866c582e4a90f8b24810ae4067b3558f7cdbbdf
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 9696

service:
  main:
    controller: main
    ports:
      http:
        port: 9696
