apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: 2.7.0
    helm:
      values: |
        service:
          type: ClusterIP
          main:
            port: 8096

        ingress:
          enabled: false

        securityContext:
          privileged: true 

        extraVolumeMounts:
          - name: render-device
            mountPath: /dev/dri
          - name: media-root
            mountPath: /media

        extraVolumes:
          - name: render-device
            hostPath:
              path: /dev/dri
          - name: media-root
            nfs:
              server: 10.9.8.30
              path: /mnt/media

        persistence:
          config:
            enabled: true
            size: 10Gi
            storageClassName: "nfs-pv"
            accessMode: ReadWriteMany
          cache:
            enabled: true
            size: 10Gi
            storageClassName: "nfs-pv"
            accessMode: ReadWriteMany

        resources:
          requests:
            cpu: 100m
            memory: 1Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
