controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/calibre-web
          tag: 0.6.26-ls373
          digest: sha256:ce91afe1778a60b0931ef2adc838bd0725679148577c19e73114d624bcfaf581
        env:
          DOCKER_MODS: "lscr.io/linuxserver/mods:universal-calibre"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /
            port: 8083
          readiness:
            enabled: true
            type: HTTP
            path: /
            port: 8083
          startup:
            enabled: true
            type: HTTP
            path: /
            port: 8083

service:
  main:
    controller: main
    ports:
      http:
        port: 8083

persistence:
  media:
    enabled: true
