controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/crocodilestick/calibre-web-automated
          tag: v4.0.6
          digest: sha256:fbf0c866e77b366f07050a6a12fee4e840b60d364485576a810109851a488eec
        env:
          NETWORK_SHARE_MODE: "true"
          TRUSTED_PROXY_COUNT: "2"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /
            port: 8083
          readiness:
            enabled: true
            type: HTTP
            path: /
            port: 8083
          startup:
            enabled: true
            type: HTTP
            path: /
            port: 8083

service:
  main:
    controller: main
    ports:
      http:
        port: 8083

persistence:
  config:
    size: 2Gi
  calibre-library:
    existingClaim: media-library-pvc
    globalMounts:
      - path: /calibre-library
        subPath: library/books
  ingest:
    existingClaim: cwa-book-ingest
    globalMounts:
      - path: /cwa-book-ingest
