apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  namespace: operations
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "iscsi-pv"
  resources:
    requests:
      storage: 5Gi
