name: homepage-admin
namespace: operations
deployPhase: services
helmManifests: true

ingress:
  enabled: true
  host: "admin"
  domainType: "public"
  port: 3000
  auth: true
  authAdmin: true
  rateLimit: true
