name: jellyfin
namespace: media
deployPhase: services
manifests: true
ingress:
  enabled: true
  host: ""
  domainType: "media"
  serviceName: jellyfin-main
  port: 8096
  auth: false
  rateLimit: false
