controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/jellyfin
          tag: 10.11.10@sha256:c0ed73678fb4ca761e0d940a92e49b95352f7f241a9be79a2c575c0099288f46
        env:
          JELLYFIN_PublishedServerUrl: "https://benplus.app" # source: globals.yaml → global.domains.media
        resources:
          limits:
            gpu.intel.com/i915: "1"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /health
            port: 8096
          readiness:
            enabled: true
            type: HTTP
            path: /health
            port: 8096
          startup:
            enabled: true
            type: HTTP
            path: /health
            port: 8096
            spec:
              initialDelaySeconds: 30
              failureThreshold: 60
              periodSeconds: 10

service:
  main:
    controller: main
    ports:
      http:
        port: 8096
  discovery:
    controller: main
    type: ClusterIP
    ports:
      discovery:
        port: 7359
        protocol: UDP

persistence:
  config:
    enabled: false
  jellyfin-config:
    existingClaim: jellyfin-config
    globalMounts:
      - path: /config
  media:
    enabled: true
  jellyfin-cache:
    existingClaim: jellyfin-cache
    globalMounts:
      - path: /config/cache
