apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config
  namespace: home-automation
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: iscsi-pv
  resources:
    requests:
      storage: 2Gi
