name: sonarr
namespace: media
deployPhase: services
commonValuesExtras:
  - templates/media-arr-common.yaml

ingress:
  enabled: true
  host: sonarr
  domainType: "internal"
  port: 8989
  auth: true
  rateLimit: true
