controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.17@sha256:b5670a3adb0f8a8b0f277feeaa69a5fbe3869ba4bb9fa7c0f0764c3b3f0e698f
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

persistence:
  media:
    enabled: true
