controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.17@sha256:60f3b6b5c7647ba2bafd81163acfe34b11117b9b834ebd7fbcc3e5f1b309c7ef
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

persistence:
  media:
    enabled: true
