controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: 4.0.17@sha256:bed3afb5d46fde809290997760f2e19d41e57d1eb34f507c485d5a8979c7cd8d
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 8989

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

persistence:
  media:
    enabled: true
