{{- if and .Values.ingress.enabled .Values.ingress.probe }}
{{- $fqdn := include "ingress-chart.fqdn" . }}
{{- $module := ternary "http_auth" "http_2xx" (.Values.ingress.auth | default false) }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  interval: 60s
  module: {{ $module }}
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
    scheme: http
  targets:
    staticConfig:
      static:
        - https://{{ $fqdn }}
      labels:
        service: {{ .Values.name }}
        tier: ingress
{{- end }}
