---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-lastfm-secret
  namespace: media
spec:
  encryptedData:
    ND_LASTFM_APIKEY: AgCn4ix+gtbIDeUop7S8RDNFPSojU1PVtskTmNaipe4mx9uFTMdRwDCaYqXqRsKVNCu1Z24jiyZrNWYA9o1LYVt4NqcKAHGHDy+QmKIoe9kiMtY7hwpJ/ciMQIK99KzPaonUkyIigU/a/gpfxD+CEEiidszjVsD1BPnZfoqB+m3itB2ofnRZ2L11Sa8yFsrFC+CLUj48uqmMr6CgZNnkCusk9wDVrA2RwATSCU4uPZ4SFJAak1BfVuM4ndj1o1/r83BcJpnzt8FKZJ1uiUZvHqbcW/WH9FHIolUGOUv3oJARpNIsroyyjbBe3SW7hKsKqVL8EoxD3tjDJohoTwhLKbVJQdleViMftUacUYaAWRLhF9eGfDFU9RSggP57S9pCaS6fC4Jd8sTWfqwoSxtyHvMg+RhQsWdY3+ZkpAugRFfdOgFHcvdUW/wDaeaRNj0l7iCNvdJKv4RYtYTfK7pRfM85cs9LN60nI5kI+pUyS/VzvT+6xFV2KkPPrexBRQxsgEKRcOH8TGx5xMvBTqq6Eg9/FRJYTWOE0udcZLjPx8IICmTAlzpZ1jAk0t765EaCWpOVpcuY+HyZ+/k3fSSSEBDaL4tOJcl4TT/aTKlfBC3gYTxgADROtbaEUri0xnOyODW/oO4ARG205bqcsOGXPLItBil38ZfQ7FlEy/zD7nx9F8/X+YXOSmwueKGGsmhSa7kRfZThegpZrOl8+an9OfLXZJnXw1sOprDoiUhPYeUegw==
    ND_LASTFM_SECRET: AgBPIPqOZEXEYlzcyF5uJ2u6ULruI6+zWXGqtozehZ0ajzBOREsefo0y0hfAlvCAizbq1g+QSDPONfYqrTfD3kX9bDB0U6QZDtD/dC7hJkF3aQgb8wkGkPutWOpzP92RC5LmHF1yiC0D2bRwMP5Edh7Y74XCvg5IK+nckcrH1OpbxAy04lxOUBsNhnmozOFgkRXgZA4n2kSDiK8arCNCYHQCTJBVUyPWdUugSulnmXYqPSdvIiDs2xGF6gSrpvloasYzBCmqe+fsculVrxe5D9zp1IEOXyNljbmVxsFtSAbbWIk+Xx2hwqkkNW4iZMpu+pPilD5a8yuQSJem0PY7LO3xqfye0UV8tYzfItP3NxG71MMbrOD2Y9Zozb1lDbnVBsTYMXawg+YD61GjablojTtC1aRa4XIvFo9UqZXPaIMUO9P1D58nx06/kekNEcRzOvb0q67Vcsybbo2AIbCWCmnFHhah/Gako1/7ZGMWLVOSRYGLAJtcjgtfFXhulr4SQn1Y70F8B1ewzOXVcQPICQhksRDmFq01mh7iVoqsAdG+aLFDE1kJsq5Wq024jux/aRIXpPpUeMhfPl4KkvX16raYzbnN8A/49LBN2PIGZYeN59OZvpeS9FR6nFh62jXcgdxeiQzbpmA4OF8MHB8pXRHUKIeOPIqhpURYxRRSc/GpwI/kSct4WhqLr+RsCh+j+stPb8LX42T5Lm3KZx/vUfTR1p978NFD0GHs2NL9KW49Ig==
  template:
    metadata:
      name: navidrome-lastfm-secret
      namespace: media
