controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-server
          tag: v2.6.1
          digest: sha256:aa7fe8eec3130742d07498dac7e02baa2d32a903573810ba95ed11f155c7eac1
        env:
          DB_HOSTNAME: immich-postgres
          DB_PORT: "5432"
          DB_DATABASE_NAME: immich
          DB_USERNAME: immich
          DB_VECTOR_EXTENSION: "vectorchord"
          REDIS_HOSTNAME: redis-master.databases.svc.cluster.local
          REDIS_PORT: "6379"
          IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
        envFrom:
          - secretRef:
              name: immich-secret
        resources:
          limits:
            gpu.intel.com/i915: "1"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /api/server/ping
            port: 2283
          readiness:
            enabled: true
            type: HTTP
            path: /api/server/ping
            port: 2283
          startup:
            enabled: true
            type: HTTP
            path: /api/server/ping
            port: 2283
            spec:
              failureThreshold: 30
              periodSeconds: 5

  machine-learning:
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-machine-learning
          tag: v2.6.1-openvino
          digest: sha256:bd5aa51a9f9a17eebf17daa7731b3bacd71a4aa542ce424d3adb06552b40e905
        resources:
          limits:
            gpu.intel.com/i915: "1"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /ping
            port: 3003
          readiness:
            enabled: true
            type: HTTP
            path: /ping
            port: 3003
          startup:
            enabled: true
            type: HTTP
            path: /ping
            port: 3003
            spec:
              failureThreshold: 30
              periodSeconds: 5

  postgres:
    pod:
      securityContext:
        fsGroup: 999
    initContainers:
      rm-postmaster-lock:
        image:
          repository: busybox
          tag: latest
        command:
          - sh
          - -c
          - |
            if [ -f /data/pgdata/postmaster.pid ]; then
              echo "🧟 Zombie Lock Found: Deleting postmaster.pid"
              rm -f /data/pgdata/postmaster.pid
            fi
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/postgres
          tag: 17-vectorchord0.4.3-pgvector0.8.1
          digest: sha256:79b95b795f0911e95ffa4d092a2162c4d81a984d5629bc8f786afe0bc0657671
        env:
          POSTGRES_DB: immich
          POSTGRES_USER: immich
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PASSWORD
          POSTGRES_INITDB_ARGS: "--data-checksums"
          PGDATA: "/data/pgdata"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 5432
          readiness:
            enabled: true
            type: TCP
            port: 5432
          startup:
            enabled: true
            type: TCP
            port: 5432
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 2283
  machine-learning:
    controller: machine-learning
    ports:
      http:
        port: 3003
  postgres:
    controller: postgres
    ports:
      tcp:
        port: 5432

persistence:
  config:
    enabled: false
  library:
    existingClaim: media-library-pvc
    advancedMounts:
      main:
        main:
          - path: /usr/src/app/upload
            subPath: immich
  pgdata:
    existingClaim: immich-pgdata
    advancedMounts:
      postgres:
        rm-postmaster-lock:
          - path: /data
        main:
          - path: /data
  model-cache:
    existingClaim: immich-model-cache
    advancedMounts:
      machine-learning:
        main:
          - path: /cache
