controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/pairdrop
          tag: 1.11.2@sha256:a3aa03fa0f21eb2b553a80186bc7c0a1a8a1451d6dbd75b62bb5c3858f2d1d96
        env:
          WS_FALLBACK: "true"
          RATE_LIMIT: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 3000
          readiness:
            enabled: true
            type: TCP
            port: 3000
          startup:
            enabled: true
            type: TCP
            port: 3000
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

persistence:
  config:
    enabled: false
