controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/pairdrop
          tag: v1.11.2-ls144@sha256:15b6792fcd486d8ebd1853dbfb0419188ca92035da2f29f75eb18b5390fa25d1
        env:
          WS_FALLBACK: "true"
          RATE_LIMIT: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 3000
          readiness:
            enabled: true
            type: TCP
            port: 3000
          startup:
            enabled: true
            type: TCP
            port: 3000
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

persistence:
  config:
    enabled: false
