controllers:
  main:
    containers:
      main:
        image:
          repository: stirlingtools/stirling-pdf
          tag: latest
          digest: sha256:c6ed2a3d2f700f083c03b6eca2d2db376d365d0fd9ddb73ba98ad3b6fae1f113
        env:
          SECURITY_ENABLELOGIN: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8080
          readiness:
            enabled: true
            type: TCP
            port: 8080
          startup:
            enabled: true
            type: TCP
            port: 8080
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

persistence:
  config:
    enabled: false
  stirling-pdf-config:
    existingClaim: stirling-pdf-config
    globalMounts:
      - path: /configs
  media:
    enabled: false
