controllers:
  main:
    containers:
      main:
        image:
          repository: stirlingtools/stirling-pdf
          tag: latest
          digest: sha256:7f0385362022ebddbecec0f00892074623ecd00e0ef93b180d8a4d65b3e8dd20
        env:
          SECURITY_ENABLELOGIN: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8080
          readiness:
            enabled: true
            type: TCP
            port: 8080
          startup:
            enabled: true
            type: TCP
            port: 8080
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

persistence:
  config:
    enabled: false
  stirling-pdf-config:
    existingClaim: stirling-pdf-config
    globalMounts:
      - path: /configs
  media:
    enabled: false
