controllers:
  main:
    containers:
      main:
        image:
          repository: stirlingtools/stirling-pdf
          tag: latest@sha256:3b3670fce70b396ec56ba380a3cc7858e0abf83fe13f31c88f7737847763a396
        resources:
          requests:
            memory: 768Mi
        env:
          SECURITY_ENABLELOGIN: "false"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8080
          readiness:
            enabled: true
            type: TCP
            port: 8080
          startup:
            enabled: true
            type: TCP
            port: 8080
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

persistence:
  config:
    enabled: false
  stirling-pdf-config:
    existingClaim: stirling-pdf-config
    globalMounts:
      - path: /configs
  media:
    enabled: false
