apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data-block
  namespace: operations
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  storageClassName: proxmox-retained
  volumeName: filebrowser-data-block
  resources:
    requests:
      storage: 4Gi
