controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/bazarr
          tag: v1.6.1-ls364@sha256:d24bd0048c759a468970989e9df11a6b96a7628d556d00f923e60a35ba59237b
        envFrom:
          - secretRef:
              name: bazarr-secret
        probes:
          liveness:
            spec:
              httpGet:
                port: 6767
          readiness:
            spec:
              httpGet:
                port: 6767
          startup:
            spec:
              httpGet:
                port: 6767
service:
  main:
    ports:
      http:
        port: 6767

persistence:
  scripts:
    type: configMap
    name: bazarr-scripts
    defaultMode: 0755
    globalMounts:
      - path: /scripts
