controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/bazarr
          tag: 1.5.6@sha256:95f27692c3de6dbe130cd035d342d8138ec74ade7b62cfc52e11ae222c52c855
        envFrom:
          - secretRef:
              name: bazarr-secret
        probes:
          liveness:   { port: 6767 }
          readiness:  { port: 6767 }
          startup:    { port: 6767 }

service:
  main:
    ports:
      http:
        port: 6767

persistence:
  scripts:
    type: configMap
    name: bazarr-scripts
    defaultMode: 0755
    globalMounts:
      - path: /scripts
