controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/bazarr
          tag: 1.5.6@sha256:8e48a2950e3806a2a914fe031fa21b1c0a0f2824eede4ea747e26213e941fbf2
        envFrom:
          - secretRef:
              name: bazarr-secret
        probes:
          liveness:
            port: 6767
          readiness:
            port: 6767
          startup:
            port: 6767
service:
  main:
    ports:
      http:
        port: 6767

persistence:
  scripts:
    type: configMap
    name: bazarr-scripts
    defaultMode: 0755
    globalMounts:
      - path: /scripts
