controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/alexbakker/alertmanager-ntfy
          tag: 1.2.0@sha256:3bff1d075a144244dd3dc15a68557ff4a2cac6af5299f793b32fecaa1dea6cb2
        args: ["--configs", "/config/config.yml,/auth/auth.yml"]
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

persistence:
  config:
    enabled: false
  app-config:
    enabled: true
    type: configMap
    name: alertmanager-ntfy-config
    globalMounts:
      - path: /config
        readOnly: true
  auth-config:
    enabled: true
    type: secret
    name: alertmanager-ntfy-auth
    globalMounts:
      - path: /auth
        readOnly: true
