apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-config
  namespace: operations
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "iscsi-pv"
  resources:
    requests:
      storage: 1Gi
