controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
        env:
          ND_MUSICFOLDER: "/data/library/music"
          ND_DATAFOLDER: "/config"
          ND_ENABLETRANSCODINGCONFIG: "true"
          ND_SCANNER_SCHEDULE: "@every 5m"
          ND_ENABLESHARING: "true"
          ND_EXTAUTH_TRUSTEDSOURCES: "10.42.0.0/16"
          ND_EXTAUTH_USERHEADER: "X-authentik-username"
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 4533
          readiness:
            enabled: true
            type: TCP
            port: 4533
          startup:
            enabled: true
            type: TCP
            port: 4533

service:
  main:
    controller: main
    ports:
      http:
        port: 4533

persistence:
  media:
    enabled: true
