controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.62.0@sha256:c4b5cb36a790b3eb63ca6a68bbe2fe149c2d7fa2e586f7a480e61db630e6664b
        env:
          ND_MUSICFOLDER: "/data/library/music"
          ND_DATAFOLDER: "/config"
          ND_ENABLETRANSCODINGCONFIG: "true"
          ND_SCANNER_SCHEDULE: "@every 5m"
          ND_ENABLESHARING: "true"
          ND_EXTAUTH_TRUSTEDSOURCES: "10.42.0.0/16"
          ND_EXTAUTH_USERHEADER: "X-authentik-username"
        envFrom:
          - secretRef:
              name: navidrome-lastfm-secret
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 4533
          readiness:
            enabled: true
            type: TCP
            port: 4533
          startup:
            enabled: true
            type: TCP
            port: 4533

service:
  main:
    controller: main
    ports:
      http:
        port: 4533

persistence:
  media:
    enabled: true
