controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.60.3
          digest: sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
        env:
          ND_MUSICFOLDER: "/data/library/music"
          ND_DATAFOLDER: "/config"
          ND_ENABLETRANSCODINGCONFIG: "true"
          ND_SCANNER_SCHEDULE: "@every 5m"
          ND_ENABLESHARING: "true"
          ND_EXTAUTH_TRUSTEDSOURCES: "10.42.0.0/16"
          ND_EXTAUTH_USERHEADER: "X-authentik-username"
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /api/ping
            port: 4533
          readiness:
            enabled: true
            type: HTTP
            path: /api/ping
            port: 4533
          startup:
            enabled: true
            type: HTTP
            path: /api/ping
            port: 4533

service:
  main:
    controller: main
    ports:
      http:
        port: 4533

persistence:
  media:
    enabled: true
