controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          readiness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          startup:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80

service:
  main:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    size: 2Gi
  media:
    enabled: true
