controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.34.0@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          readiness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          startup:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80

service:
  main:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    size: 2Gi
  media:
    enabled: true
