controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.36.1@sha256:3528a93b6442ffe54bd46771bbbab7c97084e1101071586d9dc2254f30bb4358
        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          readiness:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80
          startup:
            enabled: true
            type: HTTP
            path: /healthcheck
            port: 80

service:
  main:
    controller: main
    ports:
      http:
        port: 80

persistence:
  config:
    size: 2Gi
  media:
    enabled: true
